version: '2'

services:
  web: 
    build: .

    image: node:16
    depends_on: 
      - db

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/jobs_development"
      NODE_ENV: "development"

    networks:
      - api-sequelize-jobs

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "49555:5432"

    networks:
      - api-sequelize-jobs

networks:
  api-sequelize-jobs:
    driver: bridge